### ISSUE TITLE
no configuration file

### ISSUE THREAD

**Issue by Leaderofepic134** [laggron42/BallsDex-DiscordBot#20]
![image](https://user-images.githubusercontent.com/81798660/210272598-f346faed-e071-47a1-8f6f-6c51a6ab709a.png)

**Comment by DeeR5491** [comment]
You need to do docker compose build in the same directory as the docker-compose.yml file

**Comment by EthanTheFrancaboo** [comment]
thats the root.. docker-compose.yml is on the root.. where it tells you to use docker compose build..

**Comment by MilyvRUN** [comment]
time="2023-01-19T20:15:20+01:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-01-19T20:15:20+01:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-01-19T20:15:20+01:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string." 
What about this?
