### ISSUE TITLE
Got randomly blacklisted from using the bot

### ISSUE THREAD

**Issue by Switzerland1128** [laggron42/BallsDex-DiscordBot#23]
Hello, this morning I woke up and decided to catch a countryball after like a week. Then the bot said I was blacklisted for some reason that the bot didn't tell me. Can I know why was I blacklisted and if I could be unblacklisted?
![Screenshot_2023-01-19-10-36-23-05_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/123084328/213451564-32ee8eb5-f1a7-42ca-a680-a6936eefd995.jpg)

**Comment by laggron42** [comment]
Please do not use the repo's issues for problems about the main instance, use the [official support server](https://discord.gg/ballsdex) instead, and open a ticket here.

The issues here are meant for what's directly concerning the bot's source code, not how the main instance is handled.
