### ISSUE TITLE
Bot does not respond

### ISSUE THREAD

**Issue by RamAgentPcArsonist** [laggron42/BallsDex-DiscordBot#24]
Hello, Is there an issue with the bot right now? Because I tryna watch my countryballs lists, and an error "The application did not respond" appeared, I tried again with the /help command but it does the same.
If it is a blacklist let me know so I can appeal it
Thanks you ![Screenshot_20230122_210358.jpg](https://user-images.githubusercontent.com/105162600/213937760-a9805c08-b255-44b1-b9ba-4717d1a7eacc.jpg)

**Comment by RamAgentPcArsonist** [comment]
small edit : The discord's link isn't available anymore

**Comment by HabGesehen** [comment]
This happened to me too. This is not a blacklist. I think a possible solution (havnt tried yet) is to put the bots role at the top of the role hierarchy.

**Comment by laggron42** [comment]
Don't use this repo for issues with `Ballsdex#0677` (the official bot), use [the official server](https://discord.gg/ballsdex) instead.

Issues in this repo should be about issues with the bot's code, features that could be added or verified bugs.
