### ISSUE TITLE
Admin commands wont work for me.

### ISSUE THREAD

**Issue by ZhenPlaz** [laggron42/BallsDex-DiscordBot#26]
I am an administrator on a server, but none of the Admin commands work.

**Comment by laggron42** [comment]
Have you setup the 3 additional env vars in `.env`?

If it worked, you should see that in your logs ![](https://user-images.githubusercontent.com/23153234/215275607-772d56be-6192-4fa5-9833-6677a9f0aa98.png)

**Comment by ZhenPlaz** [comment]
what

**Comment by ZhenPlaz** [comment]
could you like explain how

**Comment by laggron42** [comment]
Eh... Join the [Discord server](https://discord.gg/ballsdex) and ask for the self-hosted role I guess
