### ISSUE TITLE
Enquiry regarding Balls

### ISSUE THREAD

**Issue by MaxMady** [laggron42/BallsDex-DiscordBot#27]
Hey there, just wanted ask that, where can I get the spawn images and images used for emojis used in the bot? I am able to find only a few of them in the Polandballs website.
Would be great if its open sourced and not in sqlite format!

**Comment by laggron42** [comment]
Redistributing images for download might be a problem regarding the licences for the different artworks we used. As we migrate to a point where most of the artworks are from the community, I'll consider this again.
