### ISSUE TITLE
what does it mean

### ISSUE THREAD

**Issue by Kompridi** [laggron42/BallsDex-DiscordBot#32]
what does it mean by "root of the repository" (im making my own variant of the bot called Britishdex for britishballs)

i've never worked with docker before

**Comment by Kompridi** [comment]
also where do i run `docker compose build`????

**Comment by Kompridi** [comment]
you need to clarify the instructions of running the bot so people dont end up like me

**Comment by PredaaA** [comment]
Instructions are already clear enough. Additional informations not related to the project can be found with one Google search.

**Comment by Kompridi** [comment]
i searched up "root of the repository" but nothing came up that i could understand

**Comment by Kompridi** [comment]
i still dont know where the root of the repository is i dont know what it means im not familiar with coding that much

**Comment by GamingadlerHD** [comment]
The root floder is the floder where everything is located. So you downloaded Ballsdex.zip or something, then you unzip it!
Now you have a floder called ballsdex an in it are files like README the pyproject and the .github floder at the top. If you are in this floder, you are in the "root of the repository". Here you have to create the .env file. You can rightclick an select Open in Terminal... here you will enter the commands.

**Comment by Kompridi** [comment]
which program do i use to open the .env file in terminal

**Comment by Kompridi** [comment]
im still getting errors running `docker compose up -d`

**Comment by Kompridi** [comment]
i've created the .env file in the correct place

**Comment by Kompridi** [comment]
i've gone to the integrated terminal and input the commands but i still get errors

**Comment by Kompridi** [comment]
![whatdoido](https://user-images.githubusercontent.com/125587516/219460817-d40416f1-e0b6-41da-8de4-dd7ee5c8457d.png)

**Comment by Kompridi** [comment]
what am i doing wrong?

**Comment by Kompridi** [comment]
ah ok

**Comment by Kompridi** [comment]
![whatdoesthismean](https://user-images.githubusercontent.com/125587516/219463893-9a3bbfd1-fa8b-473a-8373-67213cc08b88.png)
what do i do about this

**Comment by GamingadlerHD2** [comment]
Open the docker Applikation on your pc (just normaly start it like a Programm) and try again.

**Comment by Kompridi** [comment]
am i meant to sign up to it?

**Comment by GamingadlerHD2** [comment]
No, just open, so it starts

**Comment by Kompridi** [comment]
still comes up with error

**Comment by Kompridi** [comment]
am i meant to open the thing on there?

**Comment by Kompridi** [comment]
what do i doooooo the error still shows up

**Comment by GamingadlerHD2** [comment]
https://youtu.be/UChRfTztE64 watch a Tutorial

**Comment by Kompridi** [comment]
the error in question is a docker daemon error

**Comment by Kompridi** [comment]
pls help

**Comment by Kompridi** [comment]
its annoying me i cant fix it

**Comment by Kompridi** [comment]
![Screenshot 2023-02-16 222209](https://user-images.githubusercontent.com/125587516/219500618-f2486242-a6a3-40ae-a846-fb8cc455834c.png)

**Comment by Kompridi** [comment]
nevermind problem solved i just had to update my computer

**Comment by Kompridi** [comment]
nevermind i have a new issue
`docker compose build` did work but now `docker compose up` is giving me errors
![Screenshot 2023-02-17 100823](https://user-images.githubusercontent.com/125587516/219615330-1f358cdb-a448-4e09-947a-1bcc07297314.png)

**Comment by Kompridi** [comment]
help please?

**Comment by Kompridi** [comment]
helpl sokmeone

**Comment by flaree** [comment]
Be patient. Someone will help when they can, spamming an issue is not going to help whatsoever and will probably just end with you being banned from interacting with the repo.

**Comment by Kompridi** [comment]
sorry

**Comment by Kompridi** [comment]
just wanna mention that it does try to run both but quickly encounters the error
