### ISSUE TITLE
token not found

### ISSUE THREAD

**Issue by swedishcheese289** [laggron42/BallsDex-DiscordBot#34]
Skipping virtualenv creation, as specified in config file.
stateballsdex2-bot-1              | ------------------ BallsDex bot ------------------
stateballsdex2-bot-1              |                Collect countryballs               
stateballsdex2-bot-1              |           Discord bot made by El Laggron          
stateballsdex2-bot-1              | 
stateballsdex2-bot-1              |  Bot version:              1.4.0
stateballsdex2-bot-1              |  Discord.py version:      2.2.0a
stateballsdex2-bot-1              | 
stateballsdex2-bot-1              | 2023-02-17 19:46:50 ERROR    ballsdex Token not found!
stateballsdex2-bot-1              | You must provide a token with the BALLSDEXBOT_TOKEN env var.
i have it named .env, i copied and pasted it and i entered the token? what happened

**Comment by Kompridi** [comment]
the .env file is prob not actually .env

**Comment by laggron42** [comment]
As Kompridi said, the `.env` file is probably wrong. If Windows says it's a text document, then it's named `.env.txt` which doesn't work.

Try to enable file extensions to properly rename the file.
