### ISSUE TITLE
finally got the bot online... but now i cant access the admin panel

### ISSUE THREAD

**Issue by Kompridi** [laggron42/BallsDex-DiscordBot#35]
cant access the admin panel
BUT i did notice that when i ran `docker compose up -d` it said `admin-panel: error` so that might have something to do with it

**Comment by Kompridi** [comment]
should i re-run the command or....

**Comment by Kompridi** [comment]
![Discord — Mozilla Firefox 17_02_2023 22_32_55](https://user-images.githubusercontent.com/125587516/219808425-d6c2eeea-e896-4d37-a287-53ff396026ff.png)
this is what it gives me

**Comment by swedishcheese289** [comment]
how do you evenget it online i cant its something about an invalid token buti put it right and named it .env

**Comment by Kompridi** [comment]
i never had issues with the token thing
but i got to here by constantly restarting my computer

**Comment by Kompridi** [comment]
bruh now docker keeps crashing and closing randomly and hiding my stuff

**Comment by Kompridi** [comment]
prob just a storage issue on my end though

**Comment by Kompridi** [comment]
ok i redid the whole process and everything finally worked...
except the admin panel.
IT STILL WONT LOAD.

**Comment by Kompridi** [comment]
oh lookie here
its because the github page put it as https 

ITS HTTP, LOL.
