### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by DarkTK** [laggron42/BallsDex-DiscordBot#39]
I'm having issues with docker, no matter what I try it won't work, I kept getting errors while opening docker desktop, I reset my computer but then after that I couldn't even download it and I don't know what I'm doing wrong

**Comment by laggron42** [comment]
Can you move this to the [Discord server](https://discord.gg/ballsdex)? Say you're coming from Github and ask for the self-hosted role in the general chat
