### ISSUE TITLE
spawn issue

### ISSUE THREAD

**Issue by axolotlskip** [laggron42/BallsDex-DiscordBot#41]
I've made a bot like BallsDex (around 18 february 2023) , sometimes (very rarely) balls spawns correctly but most of the time the balls doesn't spawn even with sending a lot of messages. How can I fix this ?

**Comment by laggron42** [comment]
No need to reopen different issues for the same thing.

Balls spawn based on message activity, it's not very high. If they spawn, then it works. Do note that restarting the bot restarts the counter, thus making it appear even more rare.
