### ISSUE TITLE
Once I updated my bot to 2.0.3, The b.spawnball doesn't work. Is that a bug or something?

### ISSUE THREAD

**Issue by MonarPio** [laggron42/BallsDex-DiscordBot#48]

**Comment by laggron42** [comment]
It's normal, the command was removed in favor of `/admin spawn`.

If you have trouble setting up the `/admin` command, give [this wiki article](https://github.com/laggron42/BallsDex-DiscordBot/wiki/Installing-Ballsdex#filling-the-values) a read, or join the self-hosting discord server, also available in the wiki sidebar
