### ISSUE TITLE
Docker Problem

### ISSUE THREAD

**Issue by StuffCreations** [laggron42/BallsDex-DiscordBot#50]
On Docker whenever I do "docker compose up" it works perfectly, but then stops and says Error Code 5001 Missing access. And I'm trying to fix it, could you help me?

**Comment by flaree** [comment]
Please show information.

**Comment by StuffCreations** [comment]
Different problem now it says this.
![DF5B98FB-49F4-4BA0-B386-D04546FFE3C0](https://user-images.githubusercontent.com/126376294/229303849-75cc2ac5-1a09-48eb-b8f7-2887566601fd.jpg)

**Comment by StuffCreations** [comment]
So how do I fix it?
