### ISSUE TITLE
Docker Not Starting

### ISSUE THREAD

**Issue by Strenatos** [laggron42/BallsDex-DiscordBot#51]
"An unexpected error occurred"

"Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/desktop/windows/troubleshoot/#virtualization"

what do i do?

**Comment by laggron42** [comment]
Virtualization is something you need to enable in the BIOS, something that differs for every computer. Try to search on Google how this would work with the brand of your computer.

You can also follow the instructions for installing without Docker.

Closing this as this is out of scope of the bot.
