### ISSUE TITLE
The config issue

### ISSUE THREAD

**Issue by GamingLina0509** [laggron42/BallsDex-DiscordBot#62]
how does the config part work? when i try out the bot, it does not have the command /config
![Screenshot 2023-04-08 12 52 39 PM](https://user-images.githubusercontent.com/78812341/230733365-bb71709c-81dd-4da8-af65-de5e4b2cecb8.png)

**Comment by laggron42** [comment]
What did you do to the code lmao, nothing is in order, it's invalid Python code.

Editing the code is not supported, roll back to its original state and that's all.
